'use strict';
const $=id=>document.getElementById(id);const editor=$('editor');const paper=$('resume');const renderer=PaperRenderer.create(marked,{readLineStyle,lineStyleAttributes});
const renderMode=new URLSearchParams(location.search).get('view')==='render';if(renderMode)document.body.classList.add('render-mode');
let current=PaperCore.document({markdown:''}),activeId=null,activeName='',sync=null,baseline=null,saveTimer,previewTimer,selectedTemplate='projects',busy=false,previewRunning=false,pendingPreview=false,previewGeneration=0;let pdfjsPromise;let renderedPreviewKey='';

const imageDrag=PaperImageDrag.create({panel:$('pdf-pages'),reset:$('image-reset-position'),
 onBegin:revision=>{if(busy||!sync?.isConnected()||revision!==sync.getRevision())return false;setBusy(true);sync.pause();return true;},
 onEnd:()=>{sync?.resume();setBusy(false);schedulePreview();},onError:message=>{notify(message);renderedPreviewKey='';},
 onMove:async(imageId,position,revision)=>{const id=activeId;await sync.flush();if(id!==activeId||!sync.isConnected()||revision!==sync.getRevision())throw new Error('正文已更新，请在新预览中重新移动图片。');const result=await request(api('/api/image-position'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedRevision:revision,imageId,position})});sync.adopt(result.document);imageDrag.setRevision(result.document.revision);}
});
const api=(path,id=activeId)=>path+(id?'?id='+encodeURIComponent(id):'');
async function request(url,options){const response=await fetch(url,{cache:'no-store',...options});const result=await response.json();if(!response.ok)throw new Error(result.error?.message||'操作失败');return result;}
function notify(message){const dialog=document.querySelector('dialog[open]');if(dialog&&message){let note=dialog.querySelector('.dialog-notice');if(!note){note=document.createElement('p');note.className='dialog-notice';note.setAttribute('role','alert');dialog.querySelector('form').append(note);}note.textContent=message;return;}$('notice').textContent=message;$('notice').hidden=!message;}
$('notice').addEventListener('click',()=>notify(''));
function storageKey(){return 'paper-resume-v4:'+activeId;}
function persist(){if(renderMode||!activeId)return;try{localStorage.setItem(storageKey(),JSON.stringify({document:current,baseline}));}catch{notify('浏览器草稿无法保存，请先导出 PDF。');}}
function render(){const s=current.settings;paper.innerHTML=renderer.parse(current.markdown);paper.dataset.photoHeight=s.photoHeight||'';paper._imagePositions=s.imagePositions||{};paper.dataset.theme=s.theme;paper.dataset.template=s.templateId||'';$('template-select').value=s.templateId||'';paper.dataset.font=PaperCore.settingSchema.fontFamily.enum.includes(s.fontFamily)?s.fontFamily:'custom';paper.style.setProperty('--local-font',JSON.stringify(s.fontFamily));$('custom-font-field').hidden=paper.dataset.font!=='custom';if(document.activeElement!==$('custom-font-name'))$('custom-font-name').value=paper.dataset.font==='custom'?s.fontFamily:'';paper.dataset.density=s.density;
 for(const [name,key,unit] of [['resume-font','fontSize','pt'],['margin-vertical','marginVertical','mm'],['margin-horizontal','marginHorizontal','mm'],['experience-gap','experienceGap','mm'],['experience-inner','experienceInner','mm'],['role-gap','roleGap','mm']])paper.style.setProperty('--'+name,(s[key]??(key==='roleGap'?1:''))+unit);
 paper.style.setProperty('--page-spacing',(s.pageSpacing||0)+'mm');paper.style.setProperty('--margin-top',(s.marginTop||s.marginVertical)+'mm');paper.style.setProperty('--margin-bottom',(s.marginBottom||s.marginVertical)+'mm');if(s.lineHeight)paper.style.setProperty('--custom-leading',s.lineHeight);else paper.style.removeProperty('--custom-leading');
 renderer.decorate(paper);document.fonts.ready.then(()=>renderer.decorate(paper));
 $('print-settings').textContent=`@page{size:A4;margin:${s.marginTop||s.marginVertical}mm ${s.marginHorizontal}mm ${s.marginBottom||s.marginVertical}mm}`;
 document.querySelectorAll('[data-setting]').forEach(control=>{if(control===document.activeElement)return;const k=control.dataset.setting;if(k==='photoHeight'){const manual=Object.entries(s.imagePositions||{}).find(([id])=>id.startsWith('照片:'))?.[1];control.value=manual?String(Math.round(manual.height*100)/100):(s.photoHeight||'');return;}if(k==='fontFamily'){control.value=paper.dataset.font;return;}control.value=(current.settings[k]!==''&&current.settings[k]!==undefined?current.settings[k]:(k==='photoHeight'?'':k==='roleGap'?1:k==='lineHeight'?(s.density==='compact'?1.28:1.38):s.marginVertical));});
}
function accept(doc){current=PaperCore.document(doc);if(editor.value!==current.markdown)editor.value=current.markdown;render();persist();formatState();}
function download(value,name,type){const url=URL.createObjectURL(new Blob([value],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function changed(){sync?.markDirty();render();persist();$('save-status').textContent='保存中';clearTimeout(saveTimer);saveTimer=setTimeout(()=>sync?.flush(),400);}
function formatState(){document.querySelectorAll('[data-format]').forEach(b=>b.disabled=busy||editor.selectionStart===editor.selectionEnd);}
editor.addEventListener('input',()=>{current=PaperCore.document({...current,markdown:editor.value});changed();formatState();});['select','keyup','click'].forEach(type=>editor.addEventListener(type,formatState));
async function listResumes(){const result=await request('/api/documents');$('resume-list').replaceChildren();for(const item of result.documents){const button=document.createElement('button');button.className='resume-item';button.textContent=item.name;button.dataset.id=item.id;button.setAttribute('aria-current',String(item.id===activeId));button.addEventListener('click',()=>openDocument(item.id,item.name));$('resume-list').append(button);}return result.documents;}
async function openDocument(id,name){if(busy)return;clearTimeout(saveTimer);await sync?.flush();sync?.stop();previewGeneration++;activeId=id;updateBrand();activeName=name||'';baseline=null;let initialDraft=false;current=PaperCore.document({markdown:''});
 if(!renderMode)try{const saved=JSON.parse(localStorage.getItem(storageKey())||'null');if(saved?.document){current=PaperCore.document(saved.document);baseline=saved.baseline;initialDraft=true;}else if(id==='primary'){const old=JSON.parse(localStorage.getItem('paper-resume-working-v3')||'null');if(old?.document){current=PaperCore.document(old.document);baseline=old.baseline;initialDraft=true;}else{const legacy=JSON.parse(localStorage.getItem('paper-resume-zhao-v2')||'null');if(legacy?.markdown){const settings=Object.fromEntries(Object.keys(PaperCore.defaults).filter(k=>legacy[k]!==undefined).map(k=>[k,legacy[k]]));current=PaperCore.document({markdown:legacy.markdown,settings});baseline=JSON.parse(localStorage.getItem('paper-resume-zhao-v2-synced')||'null');initialDraft=true;}}}}catch{}
 if(!activeName)activeName=PaperCore.inspect(current.markdown).headings[0]?.title||'';editor.value=current.markdown;render();$('home-view').hidden=true;$('edit-view').hidden=false;$('editor-actions').hidden=false;setSidebar(false);$('sidebar-toggle').setAttribute('aria-expanded','false');$('sync-conflict').hidden=true;$('document-name').textContent=activeName;$('document-name').hidden=false;$('pdf-pages').replaceChildren();$('preview-status').textContent='';$('fit-one').hidden=true;$('save-status').textContent='载入中';if(!renderMode)history.replaceState(null,'','?resume='+encodeURIComponent(id));
 sync=createDocumentSync({url:api('/api/document',id),getState:()=>current,applyState:doc=>{if(doc.fileName){activeName=doc.fileName;$('document-name').textContent=activeName;$('document-name').hidden=false;}accept(doc);},initialDraft,baseline,readOnly:renderMode,onError:error=>notify('连接服务失败：'+error.message),onSynced:doc=>{baseline=PaperCore.document(doc);persist();},onConflict:show=>$('sync-conflict').hidden=!show,onStatus:(mode,name)=>{if(name){activeName=name;$('document-name').textContent=name;}$('save-status').textContent=mode==='connected'?'':mode==='conflict'?'版本冲突':'本机草稿';if(mode==='connected'){if($('notice').textContent.startsWith('连接服务失败：'))notify('');if(!renderMode)schedulePreview();}}});
 await sync.start();await document.fonts.ready;render();if(!renderMode){history.replaceState(null,'','?resume='+encodeURIComponent(id));if(sync.getRevision())try{localStorage.setItem('paper-resume-last-edited',id);}catch{}await listResumes();}return current;
}
function schedulePreview(){if(renderMode||imageDrag.isDragging()||!sync?.isConnected())return;clearTimeout(previewTimer);previewTimer=setTimeout(drawPdf,$('pdf-pages').querySelector('canvas')?300:0);}
function previewSize(){const panel=$('pdf-pages'),css=getComputedStyle(panel);return {width:Math.max(1,Math.min(794,Math.floor(panel.clientWidth-parseFloat(css.paddingLeft)-parseFloat(css.paddingRight)))),ratio:Math.min(4,Math.max(1,window.devicePixelRatio||1))};}
function previewKey(id,rev,size){return [id,rev,size.width,size.ratio].join(':');}
if(!renderMode){new ResizeObserver(()=>schedulePreview()).observe($('pdf-pages'));const watchDensity=()=>{const query=matchMedia(`(resolution: ${window.devicePixelRatio}dppx)`);query.addEventListener('change',()=>{watchDensity();schedulePreview();},{once:true});};watchDensity();}
async function drawPdf(){if(previewRunning){pendingPreview=true;return;}if(!activeId||!sync?.getRevision())return;previewRunning=true;pendingPreview=false;const id=activeId,rev=sync.getRevision(),generation=previewGeneration,size=previewSize(),key=previewKey(id,rev,size);if(renderedPreviewKey===key&&$('pdf-pages').querySelector('canvas')){previewRunning=false;return;}if(!$('pdf-pages').children.length){const loading=document.createElement('p');loading.className='preview-loading';loading.textContent='正在加载PDF…';$('pdf-pages').append(loading);}
 try{const result=await request(api('/api/preview',id)+'&revision='+rev);if(id!==activeId||generation!==previewGeneration||rev!==sync.getRevision())return;
  if(!pdfjsPromise)pdfjsPromise=import('./vendor/pdf.mjs?v=6.4.299').then(module=>{module.GlobalWorkerOptions.workerSrc='./vendor/pdf.worker.mjs?v=6.4.299';return module;});const pdfjs=await pdfjsPromise;const task=pdfjs.getDocument({url:result.basePdfUrl||result.pdfUrl});const pdf=await task.promise;const fragment=document.createDocumentFragment();
  try{for(let number=1;number<=pdf.numPages;number++){const page=await pdf.getPage(number);const base=page.getViewport({scale:1});const viewport=page.getViewport({scale:size.width/base.width*size.ratio});const canvas=document.createElement('canvas');canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);await page.render({canvasContext:canvas.getContext('2d'),viewport}).promise;const block=document.createElement('div');block.className='pdf-page';block.style.width='794px';const surface=document.createElement('div');surface.className='pdf-page-surface';surface.dataset.page=number;surface.dataset.width=base.width*25.4/72;surface.dataset.height=base.height*25.4/72;surface.append(canvas);block.append(surface);const label=document.createElement('div');label.className='pdf-page-label';label.textContent=number+' / '+pdf.numPages;block.append(label);fragment.append(block);}}finally{await pdf.loadingTask.destroy();}
  if(id!==activeId||generation!==previewGeneration||rev!==sync.getRevision())return;if(imageDrag.isDragging()){pendingPreview=true;return;}$('pdf-pages').replaceChildren(fragment);imageDrag.install(result.images||[],rev);renderedPreviewKey=key;if(key!==previewKey(id,rev,previewSize()))pendingPreview=true;$('preview-status').textContent='';$('fit-one').hidden=result.pages<=1||/^::: page[ \t]*$/m.test(current.markdown);
 }catch(error){console.error('PDF preview failed:',error);if(id===activeId&&generation===previewGeneration&&rev===sync?.getRevision()){$('preview-status').textContent='预览暂不可用';const loading=$('pdf-pages').querySelector('.preview-loading');if(loading)loading.textContent='预览加载失败，正在重试…';}}
 finally{previewRunning=false;if(pendingPreview){pendingPreview=false;schedulePreview();}}
}
function inspectLayout(){const box=paper.getBoundingClientRect();const css=getComputedStyle(paper);const blocks=[...paper.querySelectorAll('h1,h2,h3,h4,p,li,.layout-row>div,img')].map(el=>{const b=el.getBoundingClientRect();return {kind:el.tagName.toLowerCase(),text:el.textContent.slice(0,60),fontSizePt:Math.round(parseFloat(getComputedStyle(el).fontSize)*.75*100)/100,topMm:(b.top-box.top)/(96/25.4),heightMm:b.height/(96/25.4),overflow:b.right>box.right+1||b.left<box.left-1||el.scrollWidth>el.clientWidth+2};});const last=Math.max(0,...blocks.map(b=>b.topMm+b.heightMm));return {estimatedPages:Math.max(1,Math.ceil((last+(parseFloat(css.paddingBottom)/(96/25.4)))/297)),remainingMmEstimated:Math.max(0,297-last-parseFloat(css.paddingBottom)/(96/25.4)),overflow:blocks.filter(b=>b.overflow),blocks};}
window.PaperApp={getState:()=>current,getRevision:()=>sync?.getRevision(),inspectLayout,renderSnapshot:doc=>{if(!renderMode)throw new Error('仅渲染快照可用');accept(doc);}};
async function home(){if(busy)return;clearTimeout(saveTimer);await sync?.flush();sync?.stop();sync=null;previewGeneration++;activeId=null;updateBrand();setSidebar(false);$('sidebar-toggle').setAttribute('aria-expanded','false');$('home-view').hidden=false;$('edit-view').hidden=true;$('editor-actions').hidden=true;$('layout-panel').hidden=true;document.body.classList.remove('layout-open');$('document-name').textContent='';$('document-name').hidden=true;$('sync-conflict').hidden=true;history.replaceState(null,'',location.pathname+'?view=home');await listResumes();}
$('new-resume').addEventListener('click',()=>{home();setSidebar(false);});$('sidebar-close').addEventListener('click',()=>{setSidebar(false);$('sidebar-toggle').setAttribute('aria-expanded','false');});$('sidebar-toggle').addEventListener('click',()=>{$('layout-panel').hidden=true;document.body.classList.remove('layout-open');setSidebar($('sidebar').hidden);$('sidebar-toggle').setAttribute('aria-expanded',String(!$('sidebar').hidden));if(!$('sidebar').hidden)listResumes().catch(error=>notify(error.message));});
$('layout-toggle').addEventListener('click',()=>{setSidebar(false);$('sidebar-toggle').setAttribute('aria-expanded','false');$('layout-panel').hidden=!$('layout-panel').hidden;document.body.classList.toggle('layout-open',!$('layout-panel').hidden);});$('layout-close').addEventListener('click',()=>{$('layout-panel').hidden=true;document.body.classList.remove('layout-open');});
document.querySelectorAll('[data-setting]').forEach(control=>control.addEventListener('change',()=>{if(!control.validity.valid)return;if(control.dataset.setting==='fontFamily'&&control.value==='custom'){$('custom-font-field').hidden=false;$('custom-font-name').focus();return;}try{current=PaperCore.document({...current,settings:PaperCore.normalizeSettings({[control.dataset.setting]:control.value},current.settings)});changed();}catch(error){notify(error.message);render();}}));
document.querySelectorAll('[data-format]').forEach(button=>{button.addEventListener('mousedown',event=>event.preventDefault());button.addEventListener('click',()=>{const start=editor.selectionStart,end=editor.selectionEnd;if(start===end)return;const delimiter={bold:'**',italic:'*',underline:'++'}[button.dataset.format];const selected=editor.value.slice(start,end);const surrounded=editor.value.slice(start-delimiter.length,start)===delimiter&&editor.value.slice(end,end+delimiter.length)===delimiter;
 if(surrounded)editor.setRangeText(selected,start-delimiter.length,end+delimiter.length,'select');else if(selected.startsWith(delimiter)&&selected.endsWith(delimiter))editor.setRangeText(selected.slice(delimiter.length,-delimiter.length),start,end,'select');else {editor.setRangeText(delimiter+selected+delimiter,start,end,'select');editor.setSelectionRange(start+delimiter.length,end+delimiter.length);}editor.focus();editor.dispatchEvent(new Event('input'));});});
function setBusy(value){busy=value;$('smart-layout').textContent=value?'排版中…':'一键排版';editor.disabled=value;document.querySelectorAll('[data-setting],#template-select,#custom-font-name,#smart-layout,#fit-one,#pdf-download,#image-open,#new-resume').forEach(c=>c.disabled=value);$('link-open').disabled=value;formatState();}
async function autoLayout(mode='smart'){
 if(busy)return;setBusy(true);const connection=sync;
 try{await connection?.flush();if(!connection?.isConnected()){notify('请先连接服务或处理版本冲突。');return;}connection.pause();const result=await request(api('/api/layout'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedRevision:connection.getRevision(),mode})});if(result.fits)connection.adopt(result.document);else notify(result.message);}
 catch(error){notify(error.message);}finally{connection?.resume();setBusy(false);}
}
$('smart-layout').addEventListener('click',()=>autoLayout());$('fit-one').addEventListener('click',()=>autoLayout('one-page'));
$('pdf-download').addEventListener('click',async()=>{await sync?.flush();if(!sync?.isConnected()){notify('请先保存修改或处理版本冲突。');return;}const button=$('pdf-download');button.disabled=true;try{const response=await fetch(api('/api/pdf')+'&revision='+sync.getRevision()+'&download=1');if(!response.ok){const err=await response.json();throw new Error(err.error?.message||'导出失败');}download(await response.blob(),activeName+'.pdf','application/pdf');}catch(error){notify(error.message);}finally{button.disabled=false;}});
async function readFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('文件读取失败'));reader.onload=()=>resolve(reader.result.split(',')[1]);reader.readAsDataURL(file);});}
async function gallery(){const result=await request('/api/templates');$('template-gallery').replaceChildren();for(const t of result.templates.filter(t=>t.gallery!==false)){const card=document.createElement('button');card.className='template-card';card.dataset.template=t.id;const frame=document.createElement('div');frame.className='template-image';const img=document.createElement('img');img.src='docs/templates/'+t.id+'.png';img.alt=t.name+'模板效果';frame.append(img);if(t.id==='bilingual'){frame.classList.add('bilingual-preview');img.alt='中文页';const english=document.createElement('img');english.src='docs/templates/bilingual-en.png';english.alt='英文页';frame.append(english);}const title=document.createElement('strong');title.textContent=t.name;const subtitle=document.createElement('span');subtitle.textContent=t.description;card.append(frame,title,subtitle);card.addEventListener('click',()=>{selectedTemplate=t.id;$('bilingual-hint').hidden=t.id!=='bilingual';$('create-title').textContent=t.name;$('resume-name').value='';$('resume-file').value='';$('create-dialog').querySelector('.dialog-notice')?.remove();$('create-dialog').showModal();});$('template-gallery').append(card);}}
$('create-close').addEventListener('click',()=>$('create-dialog').close());$('create-form').addEventListener('submit',async event=>{event.preventDefault();const button=$('create-submit');button.disabled=true;button.textContent='排版中…';try{const file=$('resume-file').files[0];if(file&&file.size>25*1024*1024)throw new Error('文件不能超过 25MB。');const body={name:$('resume-name').value,template:selectedTemplate,...(file?{fileName:file.name,data:await readFile(file)}:{})};const result=await request('/api/documents',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});$('create-dialog').close();await openDocument(result.id,result.name);if(result.warnings.length)notify(result.warnings.join('\n'));}catch(error){notify(error.message);}finally{button.disabled=false;button.textContent='确定';}});
function imagePositions(){const select=$('image-position');if($('image-kind').value==='qr'){select.replaceChildren(new Option('右上角','right'),new Option('左上角','left'));select.hidden=false;return;}select.replaceChildren(new Option('左上角',''));const headings=PaperCore.inspect(editor.value).headings;for(const heading of headings){if(headings.filter(h=>h.title===heading.title).length===1)select.add(new Option('行内：'+heading.title,heading.title));}select.hidden=$('image-kind').value!=='logo';}
$('image-open').addEventListener('click',()=>{imagePositions();$('image-dialog').showModal();});$('image-kind').addEventListener('change',imagePositions);$('image-close').addEventListener('click',()=>$('image-dialog').close());
$('image-form').addEventListener('submit',async event=>{event.preventDefault();await sync.flush();if(!sync.isConnected())return notify('请先保存修改或处理版本冲突。');try{const file=$('image-file').files[0];if(!file||file.size>2*1024*1024)throw new Error('图片不能超过 2MB。');const kind=$('image-kind').value;const result=await request(api('/api/image'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedRevision:sync.getRevision(),data:await readFile(file),kind,position:kind==='qr'?$('image-position').value:kind==='photo'?'right':'left',...(kind==='logo'&&$('image-position').value?{heading:$('image-position').value}:{})})});sync.adopt(result.document);$('image-dialog').close();}catch(error){notify(error.message);}});
$('draft-download').addEventListener('click',()=>download(current.markdown,'未同步草稿.md','text/markdown'));$('sync-load').addEventListener('click',()=>sync.loadLatest());
window.paperReady=(async()=>{if(renderMode){await openDocument('primary');return current;}const [,documents]=await Promise.all([gallery(),listResumes()]);const query=new URLSearchParams(location.search);if(query.get('view')==='home')return current;let remembered;try{remembered=localStorage.getItem('paper-resume-last-edited');}catch{}const selected=documents.find(d=>d.id===query.get('resume'))||documents.find(d=>d.id===remembered)||[...documents].sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt))[0];if(selected)await openDocument(selected.id,selected.name);else history.replaceState(null,'',location.pathname);return current;})().catch(error=>{notify(error.message);throw error;});

$('document-name').addEventListener('click',()=>{$('rename-name').value=activeName;$('rename-dialog').showModal();});
$('rename-close').addEventListener('click',()=>$('rename-dialog').close());
$('rename-form').addEventListener('submit',async event=>{event.preventDefault();try{const result=await request(api('/api/rename'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('rename-name').value})});activeName=result.name;$('document-name').textContent=activeName;$('rename-dialog').close();await listResumes();}catch(error){notify(error.message);}});

let linkSelection;
$('link-open').addEventListener('mousedown',event=>event.preventDefault());
$('link-open').addEventListener('click',()=>{linkSelection={start:editor.selectionStart,end:editor.selectionEnd,source:editor.value,id:activeId};$('link-text').value=editor.value.slice(linkSelection.start,linkSelection.end);$('link-url').value='';$('link-dialog').showModal();($('link-text').value?$('link-url'):$('link-text')).focus();});
$('link-close').addEventListener('click',()=>$('link-dialog').close());
$('link-form').addEventListener('submit',event=>{event.preventDefault();if(!linkSelection||linkSelection.id!==activeId||linkSelection.source!==editor.value){$('link-dialog').close();notify('正文已更新，请重新选中文字插入链接。');return;}let address=$('link-url').value.trim();if(!/^[a-z][a-z0-9+.-]*:/i.test(address))address='https://'+address;try{const url=new URL(address);if(!['http:','https:','mailto:','tel:'].includes(url.protocol))throw new Error();}catch{notify('请填写有效的网站、邮箱或电话链接。');return;}const text=$('link-text').value.replace(/[\\[\]]/g,'\\$&').replace(/\r?\n/g,' ');address=address.replace(/\s/g,c=>encodeURIComponent(c)).replace(/\(/g,'%28').replace(/\)/g,'%29');editor.setRangeText('['+text+']('+address+')',linkSelection.start,linkSelection.end,'select');$('link-dialog').close();editor.focus();editor.dispatchEvent(new Event('input'));});

document.addEventListener('keydown',event=>{if(event.key==='Escape'){setSidebar(false);$('sidebar-toggle').setAttribute('aria-expanded','false');$('layout-panel').hidden=true;document.body.classList.remove('layout-open');}});

function updateBrand(){const clickable=Boolean(activeId)&&!renderMode;const brand=$('home-button');brand.dataset.clickable=String(clickable);brand.tabIndex=clickable?0:-1;if(clickable){brand.setAttribute('role','button');brand.setAttribute('aria-label','返回首页');}else{brand.removeAttribute('role');brand.removeAttribute('aria-label');}}
$('home-button').addEventListener('click',()=>{if(activeId&&!renderMode)home().catch(e=>notify(e.message));});
$('home-button').addEventListener('keydown',event=>{if(activeId&&!renderMode&&['Enter',' '].includes(event.key)){event.preventDefault();home().catch(e=>notify(e.message));}});
updateBrand();

function setSidebar(open){$('sidebar').hidden=!open;document.body.classList.toggle('sidebar-open',open);$('sidebar-toggle').setAttribute('aria-expanded',String(open));}

$('custom-font-name').addEventListener('change',()=>{try{current=PaperCore.document({...current,settings:{...current.settings,fontFamily:$('custom-font-name').value}});changed();}catch(error){notify(error.message);render();}});

$('template-select').addEventListener('change',async()=>{
 if(busy)return;const template=$('template-select').value;
 if(!template){current=PaperCore.document({...current,settings:{...current.settings,templateId:''}});changed();return;}
 setBusy(true);const connection=sync;
 try{await connection?.flush();if(!connection?.isConnected()){render();notify('请先处理版本冲突。');return;}connection.pause();const result=await request(api('/api/template'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedRevision:connection.getRevision(),template})});connection.adopt(result.document);}
 catch(error){notify(error.message);render();}
 finally{connection?.resume();setBusy(false);}
});
