const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{once}=require('node:events'),{randomUUID}=require('node:crypto');
const images=require('../lib/images'),core=require('../resume-core'),store=require('../lib/document-store'),renderer=require('../lib/render'),{main}=require('../cli');
function fixtures(count=3){const folder=path.resolve('tmp/tests/images',randomUUID());fs.mkdirSync(folder,{recursive:true});const {createCanvas}=renderer.dependency('@napi-rs/canvas');const files=Array.from({length:count},(_,index)=>'hsl('+index*47+' 55% 40%)').map((color,index)=>{const canvas=createCanvas(120,80),ctx=canvas.getContext('2d');ctx.fillStyle=color;ctx.fillRect(0,0,120,80);ctx.fillStyle='white';ctx.font='bold 32px sans-serif';ctx.fillText(String(index+1),48,52);const file=path.join(folder,`logo-${index}.png`);fs.writeFileSync(file,canvas.toBuffer('image/png'));return file;});return {folder,files};}
test('multiple corner logos persist, repeats deduplicate, portraits replace and inline logos stay with the company',async()=>{
 const {folder,files}=fixtures(),file=path.join(folder,'resume.paper.json');const markdown='::: center\n## 张三 {size=14 rule=off}\n姓名居中 · 联系方式\n:::\n\n### **工作经历** {size=11 rule=on}\n#### **微软**\n项目介绍\n### **苹果** | 2024 - 至今 {size=11}\n项目介绍\n## 教育经历\n### **示例大学（211）** {size=11}';const source=path.join(folder,'source.md');fs.writeFileSync(source,markdown);await main(['init','--file',file,'--input',source]);
 for(const input of files)await main(['image','--file',file,'--input',input,'--kind','logo']);let doc=store.load(file);assert.equal(core.inspect(doc.markdown).images.length,3);const before=doc.revision;await main(['image','--file',file,'--input',files[0],'--kind','logo']);assert.equal(store.load(file).revision,before);
 for(const input of files.slice(0,2))await main(['image','--file',file,'--input',input,'--kind','photo']);doc=store.load(file);assert.equal(core.inspect(doc.markdown).images.filter(i=>i.alt==='证件照').length,1);
 for(const heading of ['微软','苹果 | 2024 - 至今','示例大学（211）'])await main(['image','--file',file,'--input',files[0],'--kind','logo','--heading',heading]);doc=store.load(file);assert.match(doc.markdown,/\*\*苹果\*\* !\[标志\].+ \| 2024 - 至今 \{size=11\}/);assert.deepEqual(core.inspect(doc.markdown).headings.find(h=>h.title==='苹果 | 2024 - 至今').style,{size:11});assert.equal(core.inspect(doc.markdown).images.length,7);assert.doesNotMatch(doc.markdown,/教育经历 !/);assert.equal(images.insert(doc,fs.readFileSync(files[0]),'logo','苹果 | 2024 - 至今').markdown,doc.markdown);assert.throws(()=>images.insert({markdown:'### 公司\n### 公司'},fs.readFileSync(files[0]),'logo','公司'),/不存在或不唯一/);assert.throws(()=>images.image(Buffer.from('invalid image')),/PNG/);assert.throws(()=>images.image(Buffer.alloc(2*1024*1024+1)),/2MB/);
 const server=require('../lib/server').start({file,port:0,quiet:true});await once(server,'listening');const browser=await renderer.launchBrowser();try{const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.address().port+'/?view=render');await page.evaluate(()=>window.paperReady);await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.querySelectorAll('#resume img')].map(i=>i.decode()));});
 const inspect=()=>page.evaluate(()=>{const coords=el=>{const r=el.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width};};const paper=document.querySelector('#resume'),logos=[...paper.querySelectorAll('.resume-header-logo')],photo=paper.querySelector('.resume-photo'),date=paper.querySelector('.entry-date');return {logos:logos.map(coords),photo:coords(photo),loaded:[...paper.querySelectorAll('img')].every(i=>i.naturalWidth>0),dateLogo:!!date.querySelector('img'),titleLogo:!!paper.querySelector('.entry-title .resume-logo'),dateRight:coords(date).right,contentRight:coords(paper).right-parseFloat(getComputedStyle(paper).paddingRight),sectionTop:paper.querySelector('h3').getBoundingClientRect().top,headings:[...paper.querySelectorAll('h2,h3,h4,.layout-center')].map(coords)};});
 const all=await inspect();const baseline={...doc,markdown:doc.markdown.slice(doc.markdown.indexOf('::: center'))};await page.evaluate(d=>window.PaperApp.renderSnapshot(d),baseline);assert.deepEqual(await page.evaluate(()=>[...document.querySelectorAll('#resume h2,#resume h3,#resume h4,#resume .layout-center')].map(el=>{const r=el.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width};})),all.headings,'Inserting multiple corner images must not add blank lines');await page.evaluate(d=>window.PaperApp.renderSnapshot(d),doc);assert.equal(all.loaded,true);assert.ok(all.photo.bottom<=all.sectionTop-96/25.4+1,'Portrait must stay above the first section');for(const logo of all.logos)assert.ok(logo.bottom<=all.sectionTop-96/25.4+1);assert.equal(all.dateLogo,false);assert.equal(all.titleLogo,true);assert.ok(Math.abs(all.dateRight-all.contentRight)<1);const ordered=all.logos.sort((a,b)=>a.left-b.left);for(let i=1;i<ordered.length;i++)assert.ok(ordered[i].left>ordered[i-1].right);assert.ok(ordered.at(-1).right<all.photo.left);
 await page.locator('#resume').screenshot({path:path.join(folder,'combined.png')});await page.evaluate(()=>document.querySelectorAll('.resume-header-logo,.resume-photo').forEach(i=>i.style.visibility='hidden'));assert.deepEqual((await inspect()).headings,all.headings);await page.evaluate(()=>document.querySelectorAll('.resume-header-logo,.resume-photo').forEach(i=>i.parentElement.remove()));assert.deepEqual(await page.evaluate(()=>[...document.querySelectorAll('#resume h2,#resume h3,#resume h4,#resume .layout-center')].map(el=>{const r=el.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width};})),all.headings);
 await page.evaluate(d=>window.PaperApp.renderSnapshot(d),doc);await page.evaluate(async()=>document.fonts.ready);const pdf=await page.pdf({format:'A4',preferCSSPageSize:true,printBackground:true});fs.writeFileSync(path.join(folder,'combined.pdf'),pdf);assert.equal((await renderer.dependency('pdf-lib').PDFDocument.load(pdf)).getPageCount(),1);
 let sameSide=images.insert(doc,fs.readFileSync(files[0]),'photo',undefined,undefined,{position:'left'});sameSide=images.insert(sameSide,fs.readFileSync(files[0]),'logo',undefined,undefined,{position:'right'});await page.evaluate(d=>window.PaperApp.renderSnapshot(d),sameSide);const positioned=await inspect();for(const logo of positioned.logos){assert.ok(logo.right<=positioned.photo.left||logo.left>=positioned.photo.right,'Logos and photo must not overlap horizontally');}await page.locator('#resume').screenshot({path:path.join(folder,'opposite.png')});
 const paged={...doc,markdown:doc.markdown+'\n\n::: page\n\n![标志-left](templates/portrait.png)\n\n# Jack\n\n## Education\n\nExample text'};await page.evaluate(d=>window.PaperApp.renderSnapshot(d),paged);const secondLogo=await page.locator('#resume .resume-header-logo').last().boundingBox();assert.ok(Math.abs(secondLogo.x-all.headings[0].left)<1,'Logo offsets must reset on the second page');assert.ok(secondLogo.height>10);const twoPages=await page.pdf({format:'A4',preferCSSPageSize:true,printBackground:true});assert.equal((await renderer.dependency('pdf-lib').PDFDocument.load(twoPages)).getPageCount(),2);const htmlFile=path.join(folder,'export.html');fs.writeFileSync(htmlFile,require('../cli').exportHTML(doc,htmlFile,file));await page.goto('file:///'+htmlFile.replace(/\\/g,'/'));await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.querySelectorAll('.paper img')].map(i=>i.decode()));});assert.equal(await page.locator('.paper img').count(),7);
 }finally{await browser.close();await new Promise(r=>server.close(r));}
});
test('twelve left corner logos wrap within the header without moving text',{timeout:30000},async()=>{
 const {folder,files}=fixtures(12),file=path.join(folder,'resume.paper.json');let doc=core.document({markdown:'::: center\n# 李四\n产品经理 · 联系方式\n:::\n\n## 工作经历\n### **示例公司** | 2024 - 至今\n负责产品研究、需求分析与版本交付。\n\n## 教育经历\n### **示例大学**\n本科。'});store.commit(file,doc,null);
 for(const input of files)await main(['image','--file',file,'--input',input,'--kind','logo']);await main(['image','--file',file,'--input','templates/portrait.png','--kind','photo']);doc=store.load(file);assert.equal(core.inspect(doc.markdown).images.filter(i=>i.alt==='标志-left').length,12);
 const server=require('../lib/server').start({file,port:0,quiet:true});await once(server,'listening');const browser=await renderer.launchBrowser();try{const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.address().port+'/?view=render');await page.evaluate(()=>window.paperReady);await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.querySelectorAll('#resume img')].map(i=>i.decode()));});const result=await page.evaluate(()=>{const coords=el=>{const r=el.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom};};return {logos:[...document.querySelectorAll('.resume-header-logo')].map(coords),section:coords(document.querySelector('#resume h2')),paper:coords(document.querySelector('#resume')),headings:[...document.querySelectorAll('#resume h1,#resume h2,#resume h3,.layout-center')].map(coords)};});assert.ok(new Set(result.logos.map(r=>r.top)).size>1,'Many logos should wrap');for(let i=0;i<result.logos.length;i++){const r=result.logos[i];assert.ok(r.bottom<result.section.top);assert.ok(r.right<=result.section.left+42*96/25.4+1);for(const other of result.logos.slice(i+1))assert.ok(r.right<=other.left||r.left>=other.right||r.bottom<=other.top||r.top>=other.bottom,'Logos must not overlap');}
 await page.locator('#resume').screenshot({path:path.join(folder,'many-logos.png')});fs.writeFileSync(path.join(folder,'many-logos.pdf'),await page.pdf({format:'A4',preferCSSPageSize:true,printBackground:true}));const without={...doc,markdown:doc.markdown.slice(doc.markdown.indexOf('::: center'))};await page.evaluate(d=>window.PaperApp.renderSnapshot(d),without);assert.deepEqual(await page.evaluate(()=>[...document.querySelectorAll('#resume h1,#resume h2,#resume h3,.layout-center')].map(el=>{const r=el.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom};})),result.headings);
 }finally{await browser.close();await new Promise(r=>server.close(r));}
});
