const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{once}=require('node:events');const core=require('../resume-core'),images=require('../lib/images'),renderer=require('../lib/render'),{main}=require('../cli');
test('inline insertion preserves heading styles and replaces the existing logo',()=>{const png=fs.readFileSync('templates/portrait.png');const doc={markdown:'# 张三\n## 教育经历 {size=12.5}\n### **示例大学（211）** {size=11 align=left}'};const next=images.insert(doc,png,'logo','示例大学（211）');assert.match(next.markdown,/大学（211）\*\* !\[标志\].+ \{size=11 align=left\}$/);assert.deepEqual(core.inspect(next.markdown).headings[2].style,{size:11,align:'left'});assert.equal(images.insert(next,png,'logo','示例大学（211）').markdown,next.markdown);assert.doesNotMatch(next.markdown,/教育经历.+!\[/);});
test('logo defaults left, portrait defaults right, and inline logos require a heading',{timeout:30000},async()=>{
 const png=fs.readFileSync('templates/portrait.png');const file=path.resolve('tmp/tests/image-defaults',require('node:crypto').randomUUID(),'resume.paper.json');fs.mkdirSync(path.dirname(file),{recursive:true});const store=require('../lib/document-store');store.commit(file,{markdown:'# 张三\n## 教育经历\n### **示例大学**\n正文'},null);
 await main(['image','--file',file,'--input','templates/portrait.png','--kind','logo']);await main(['image','--file',file,'--input','templates/portrait.png','--kind','photo']);let doc=store.load(file);assert.match(doc.markdown,/!\[标志-left\]/);assert.match(doc.markdown,/!\[证件照\]/);assert.doesNotMatch(doc.markdown,/示例大学\*\* !/);
 doc=images.insert(doc,png,'logo','示例大学',file);assert.match(doc.markdown,/### \*\*示例大学\*\* !\[标志\]/);store.commit(file,doc,store.load(file).revision);
 const server=require('../lib/server').start({file,port:0,quiet:true});await once(server,'listening');const browser=await renderer.launchBrowser();try{const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.address().port+'/?view=render');await page.evaluate(()=>window.paperReady);await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.querySelectorAll('#resume img')].map(i=>i.decode()));});const result=await page.evaluate(()=>{const rect=s=>document.querySelector(s).getBoundingClientRect();const paper=rect('#resume'),css=getComputedStyle(document.querySelector('#resume'));return {left:rect('.resume-header-logo').left-paper.left,right:paper.right-rect('.resume-photo').right,padLeft:parseFloat(css.paddingLeft),padRight:parseFloat(css.paddingRight),inline:!!document.querySelector('h3 .resume-logo')};});assert.ok(Math.abs(result.left-result.padLeft)<1);assert.ok(Math.abs(result.right-result.padRight)<1);assert.equal(result.inline,true);const unaffected=await page.evaluate(()=>{const headings=[...document.querySelectorAll('#resume h1,#resume h2')];const bounds=()=>headings.map(el=>{const r=el.getBoundingClientRect();return [r.x,r.y,r.width,r.height];});const before=bounds();document.querySelectorAll('.resume-header-logo,.resume-photo').forEach(el=>el.style.display='none');const after=bounds();document.querySelectorAll('.resume-header-logo,.resume-photo').forEach(el=>el.style.display='');return {before,after};});assert.deepEqual(unaffected.after,unaffected.before,'Corner images must not move or narrow headings');assert.equal(await page.locator('#image-heading').count(),0);assert.equal(await page.locator('#rename-dialog label').count(),0);assert.equal(await page.locator('#page-count').count(),0);await page.goto('http://127.0.0.1:'+server.address().port+'/?resume=primary');await page.evaluate(()=>window.paperReady);await page.locator('#image-open').click();await page.locator('#image-kind').selectOption('logo');assert.equal(await page.locator('#image-position').inputValue(),'');await page.locator('#image-position').selectOption('示例大学');await page.locator('#image-file').setInputFiles('templates/portrait.png');await page.locator('#image-form button[type=submit]').click();await page.locator('#image-dialog').waitFor({state:'hidden'});assert.equal((store.load(file).markdown.match(/!\[标志(?: \{crop=[^}]+\})?\]/g)||[]).length,1);await page.locator('#image-open').click();assert.equal(await page.locator('#image-position').inputValue(),'');await page.locator('#image-close').click();
 }finally{await browser.close();await new Promise(r=>server.close(r));}
});
