const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {randomUUID}=require('node:crypto');const {once}=require('node:events');const renderer=require('../lib/render');const store=require('../lib/document-store');const importer=require('../lib/import');const templates=require('../lib/templates');const {main}=require('../cli');
test('import extracts PDF and DOCX, preserves facts, rejects image-only PDF',{timeout:30000},async()=>{
 const {PDFDocument,StandardFonts}=renderer.dependency('pdf-lib');const pdf=await PDFDocument.create();const page=pdf.addPage();const font=await pdf.embedFont(StandardFonts.Helvetica);['Example Name','Experience','Example Company 2024.01 - Present','Delivered 100 projects'].forEach((line,i)=>page.drawText(line,{x:40,y:760-i*30,size:12,font}));
 const prepared=await importer.prepare(Buffer.from(await pdf.save()),'resume.pdf','projects');assert.match(prepared.document.markdown,/# Example Name/);assert.match(prepared.document.markdown,/100 projects/);assert.match(prepared.document.markdown,/Example Company\*\* \| 2024.01 - Present/);assert.equal(prepared.document.settings.fontSize,'10.5');assert.equal(prepared.pages,1);
 const blank=await PDFDocument.create();blank.addPage();await assert.rejects(importer.prepare(Buffer.from(await blank.save()),'scan.pdf'),{code:'NO_TEXT'});
 const JSZip=renderer.dependency('jszip');const zip=new JSZip();zip.file('word/document.xml','<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body><w:p><w:r><w:t>示例姓名</w:t></w:r></w:p><w:p><w:r><w:t>工作经历</w:t></w:r></w:p><w:p><w:r><w:t>完成项目100项 &amp; 更多</w:t></w:r></w:p><w:p><w:r><w:t>岗位</w:t><w:tab/><w:t>部门</w:t></w:r></w:p></w:body></w:document>');
 const docx=await importer.prepare(await zip.generateAsync({type:'nodebuffer'}),'resume.docx','research');assert.match(docx.document.markdown,/## 工作经历/);assert.match(docx.text,/完成项目100项 & 更多/);assert.match(docx.document.markdown,/岗位    部门/);assert.equal(docx.document.settings.fontFamily,'serif');
});
test('Templates preserve content and apply presets; import dry run is read-only and commit uses revision checks',async()=>{
 const folder=path.resolve(__dirname,'../tmp/tests',randomUUID());fs.mkdirSync(folder,{recursive:true});const file=path.join(folder,'resume.paper.json');const initial=store.commit(file,{markdown:'# 原姓名\n\n保留全部内容'},null).document;
 for(const t of templates.templates){assert.ok(templates.sample(t.id).includes('\n## '));assert.ok(!templates.sample(t.id).includes('\r'));const result=templates.apply(initial,t.id);assert.equal(importer.contentAudit(initial.markdown,require('../resume-structure').parse(result.markdown)).preserved,true);assert.equal(result.settings.templateId,t.id);assert.equal(result.settings.fontFamily,templates.profiles[t.id].settings.fontFamily);};
 const input=path.join(folder,'resume.md');fs.writeFileSync(input,'# 新姓名\n\n新的完整内容');const dry=await main(['import','--file',file,'--input',input,'--template','projects','--dry-run']);assert.equal(dry.dryRun,true);assert.equal(store.load(file).revision,initial.revision);
 const changed=await main(['template','--file',file,'--name','research']);assert.equal(importer.contentAudit(initial.markdown,require('../resume-structure').parse(store.load(file).markdown)).preserved,true);
 await assert.rejects(main(['import','--file',file,'--input',input,'--expect',initial.revision]),{code:'REVISION_CONFLICT'});
 const saved=await main(['import','--file',file,'--input',input,'--template','projects','--expect',changed.revision]);assert.ok(fs.existsSync(saved.source));assert.ok(fs.existsSync(saved.backup));assert.match(store.load(file).markdown,/新的完整内容/);
});
test('old browser draft remains recoverable when switching to preview',{timeout:30000},async()=>{
 const folder=path.resolve(__dirname,'../tmp/tests',randomUUID());fs.mkdirSync(folder,{recursive:true});const file=path.join(folder,'resume.paper.json');store.commit(file,{markdown:'# 文件中的姓名'},null);const server=require('../lib/server').start({file,port:0,quiet:true});await once(server,'listening');const browser=await renderer.launchBrowser();
 try{const page=await browser.newPage();await page.addInitScript(()=>localStorage.setItem('paper-resume-zhao-v2',JSON.stringify({markdown:'# 未同步的姓名',fontSize:'10',density:'compact'})));await page.goto(`http://127.0.0.1:${server.address().port}/?resume=primary`);await page.evaluate(()=>window.paperReady);assert.equal(await page.locator('#sync-conflict').isVisible(),true);assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('paper-resume-zhao-v2')).markdown),'# 未同步的姓名');assert.equal(await page.evaluate(()=>window.PaperApp.getState().markdown),'# 未同步的姓名');}
 finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
});
