const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {randomUUID}=require('node:crypto');const {once}=require('node:events');
const core=require('../resume-core');const store=require('../lib/document-store');const renderer=require('../lib/render');const {main}=require('../cli');
const fixture=()=>{const folder=path.resolve(__dirname,'../tmp/tests',randomUUID());fs.mkdirSync(folder,{recursive:true});return {folder,file:path.join(folder,'resume.paper.json')};};
const experience=count=>'### **工作经历** {rule=on}\n\n#### **示例公司**\n::: row\n部门    产品经理 || 2024.01 - 至今\n:::\n'+Array.from({length:count},()=>'- 负责复杂项目的数据收集标注训练与效果评测并交付可靠的产品能力').join('\n');
test('real PDF one-page fit succeeds and long documents fail without overwriting',{timeout:90000},async()=>{
 const moderate=core.document({markdown:experience(40),settings:{fontSize:14,density:'airy',marginVertical:28,marginHorizontal:24,experienceInner:6,experienceGap:12}});const fit=await renderer.fit(moderate);
 assert.equal(fit.fits,true);assert.equal(fit.report.actualPages,1);assert.ok(fit.attempts[0].actualPages>1);assert.match(fit.document.markdown,/部门    产品经理/);
 assert.equal(fit.document.markdown.split('负责复杂项目').length,moderate.markdown.split('负责复杂项目').length);
 const {file}=fixture();const long=store.commit(file,{markdown:experience(180)},null).document;const result=await main(['fit','--file',file]);process.exitCode=0;
 assert.equal(result.fits,false);assert.equal(result.applied,false);assert.ok(result.report.actualPages>1);assert.equal(store.load(file).revision,long.revision);
});
test('gallery creates a separate resume; editing, photos, CLI, real pagination and PDF download work',{timeout:90000},async()=>{
 const {file}=fixture();const initial=store.commit(file,{markdown:experience(2)},null).document;const server=require('../lib/server').start({file,port:0,quiet:true});await once(server,'listening');const browser=await renderer.launchBrowser();
 try{const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const url=`http://127.0.0.1:${server.address().port}`;
  await page.goto(url+'/?view=home');await page.evaluate(()=>window.paperReady);assert.equal(await page.locator('.template-card').count(),4);assert.equal(await page.locator('#editor').isVisible(),false);assert.equal(await page.locator('#smart-layout').isVisible(),false);
  assert.equal(await page.locator('#home-button').evaluate(el=>el.tagName),'SPAN');for(const width of [1440,900,640,390]){await page.setViewportSize({width,height:1000});assert.ok(await page.locator('#template-gallery').evaluate(el=>el.scrollWidth<=el.clientWidth+1));}await page.setViewportSize({width:1440,height:1000});
  await page.locator('[data-template="projects"]').click();await page.locator('#resume-name').fill('测试简历');await page.locator('#resume-file').setInputFiles({name:'resume.txt',mimeType:'text/plain',buffer:Buffer.from('示例姓名\n工作经历\n示例公司\n研发部门 2024.01 - 至今\n完成项目100项\n教育经历\n示例大学','utf8')});await page.locator('#create-submit').click();await page.locator('#create-dialog').waitFor({state:'hidden'});await page.waitForFunction(()=>document.getElementById('save-status').textContent==='');
  await page.waitForURL('**/?resume=*');const id=new URL(page.url()).searchParams.get('resume');assert.ok(id&&id!=='primary');const target=require('../lib/library').resolve(file,id);assert.match(store.load(target).markdown,/完成项目100项/);assert.equal(store.load(file).revision,initial.revision);
  const beforeRename=store.load(target).revision;await page.locator('#document-name').click();await page.locator('#rename-name').fill('示例姓名 · 产品经理版');await page.locator('#rename-form button[type=submit]').click();await page.locator('#rename-dialog').waitFor({state:'hidden'});assert.equal(require('../lib/library').list(file).find(d=>d.id===id).name,'示例姓名 · 产品经理版');assert.equal(store.load(target).revision,beforeRename);await page.reload();await page.evaluate(()=>window.paperReady);assert.equal(await page.locator('#document-name').textContent(),'示例姓名 · 产品经理版');assert.equal(await page.locator('#layout-toggle').textContent(),'样式设置');
  await page.locator('#pdf-pages canvas').first().waitFor({state:'visible',timeout:30000});assert.equal(await page.locator('#fit-one').isVisible(),false);
  const editor=page.locator('#editor');await editor.fill(store.load(target).markdown+'\n新增一行\n\n再空一行');await page.waitForFunction(()=>document.getElementById('save-status').textContent==='');assert.match(store.load(target).markdown,/新增一行\n\n再空一行/);
  await editor.evaluate(el=>{const at=el.value.indexOf('完成项目100项');el.focus();el.setSelectionRange(at,at+8);el.dispatchEvent(new Event('select'));});await page.locator('[data-format="bold"]').click();assert.match(await editor.inputValue(),/\*\*完成项目100项\*\*/);await page.waitForFunction(()=>document.getElementById('save-status').textContent==='');
  assert.equal(await page.locator('.editor-heading').innerText(), 'B\nI\nU\n链接\n图片');await editor.evaluate(el=>{const at=el.value.indexOf('新增一行');el.focus();el.setSelectionRange(at,at+4);});await page.locator('#link-open').click();assert.equal(await page.locator('#link-text').inputValue(),'新增一行');await page.locator('#link-url').fill('javascript:alert(1)');await page.locator('#link-form button[type=submit]').click();assert.equal(await page.locator('#link-dialog .dialog-notice').isVisible(),true);await page.locator('#link-url').fill('https://example.com/project');await page.locator('#link-form button[type=submit]').click();await page.locator('#link-dialog').waitFor({state:'hidden'});assert.match(await editor.inputValue(),/\[新增一行\]\(https:\/\/example\.com\/project\)/);await page.waitForFunction(()=>document.getElementById('save-status').textContent==='');assert.match(store.load(target).markdown,/https:\/\/example\.com\/project/);
  const changed=await main(['style','--file',file,'--id',id,'--heading','工作经历','--size','11']);await page.waitForFunction(r=>window.PaperApp.getRevision()===r,changed.revision);
  await page.locator('#layout-toggle').click();await page.locator('#template-select').selectOption('internship');await page.waitForFunction(()=>!document.getElementById('template-select').disabled);assert.equal(store.load(target).settings.templateId,'internship');assert.match(store.load(target).markdown,/新增一行/);const structured=await main(['show','--file',file,'--id',id,'--structured']);assert.ok(JSON.stringify(structured.structure).includes('新增一行'));assert.ok(await page.evaluate(()=>document.getElementById('edit-view').getBoundingClientRect().right<=document.getElementById('layout-panel').getBoundingClientRect().left+1));assert.equal(await page.locator('[data-setting="fontFamily"] option').count(),10);await page.locator('[data-setting="fontFamily"]').selectOption('yahei');await page.waitForFunction(()=>document.getElementById('save-status').textContent==='');assert.equal(store.load(target).settings.fontFamily,'yahei');await page.locator('[data-setting="fontFamily"]').selectOption('custom');await page.locator('#custom-font-name').fill('Segoe UI');await page.locator('#custom-font-name').press('Tab');await page.waitForFunction(()=>document.getElementById('save-status').textContent==='');assert.equal(store.load(target).settings.fontFamily,'Segoe UI');assert.equal(await page.locator('#resume').getAttribute('data-font'),'custom');await page.reload();await page.evaluate(()=>window.paperReady);await page.locator('#layout-toggle').click();assert.equal(await page.locator('#custom-font-name').inputValue(),'Segoe UI');await page.locator('[data-setting="marginTop"]').fill('10');await page.locator('[data-setting="marginTop"]').press('Tab');await page.waitForFunction(()=>document.getElementById('save-status').textContent==='');assert.equal(store.load(target).settings.marginTop,'10');await page.locator('#layout-close').click();
  const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jD1cAAAAASUVORK5CYII=','base64');await page.locator('#image-open').click();await page.locator('#image-file').setInputFiles({name:'photo.png',mimeType:'image/png',buffer:png});await page.locator('#image-form button[type="submit"]').click();await page.locator('#image-dialog').waitFor({state:'hidden'});assert.match(store.load(target).markdown,/!\[证件照\]\(assets\//);
  const peer=store.load(target);store.commit(target,{...peer,markdown:experience(60)},peer.revision);await page.waitForFunction(r=>window.PaperApp.getRevision()!==r,peer.revision);await page.waitForFunction(()=>!document.getElementById('fit-one').hidden,{},{timeout:30000});assert.ok(await page.locator('.pdf-page').count()>1);
  await page.locator('#fit-one').click();await page.waitForFunction(()=>!document.getElementById('fit-one').disabled,{},{timeout:30000});await page.waitForFunction(()=>document.getElementById('fit-one').hidden,{},{timeout:30000});
  const downloaded=page.waitForEvent('download');await page.locator('#pdf-download').click();const download=await downloaded;const bytes=fs.readFileSync(await download.path());const {PDFDocument}=renderer.dependency('pdf-lib');assert.equal((await PDFDocument.load(bytes)).getPageCount(),1);
  await page.locator('#sidebar-toggle').click();assert.equal(await page.locator('.resume-item').count(),2);await page.locator('.resume-item[data-id="primary"]').click();await page.waitForFunction(text=>document.getElementById('editor').value===text,initial.markdown);assert.equal(await editor.inputValue(),initial.markdown);await page.reload();await page.evaluate(()=>window.paperReady);assert.equal(await editor.inputValue(),initial.markdown);
  for(const width of [900,640,390]){await page.setViewportSize({width,height:900});await page.waitForFunction(()=>document.documentElement.scrollWidth<=innerWidth+1,{},{timeout:3000});}
  assert.deepEqual(errors,[]);
 }finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
});
