const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const {randomUUID}=require('node:crypto');const core=require('../resume-core');const store=require('../lib/document-store');const library=require('../lib/library');const bilingual=require('../lib/bilingual');const {main}=require('../cli');
test('rename keeps documents, revisions and separate versions intact',async()=>{const file=path.resolve('tmp/tests',randomUUID(),'resume.paper.json');const original=store.commit(file,{markdown:'# 示例姓名\n正文'},null).document;const created=library.create(file,{name:'同名版本',document:original});await main(['rename','--file',file,'--id','primary','--name','示例姓名 · 中文']);await main(['rename','--file',file,'--id',created.id,'--name','示例姓名 · 英文']);assert.equal(store.load(file).revision,original.revision);assert.equal(store.load(created.file).revision,original.revision);assert.deepEqual(library.list(file).map(x=>x.name),['示例姓名 · 中文','示例姓名 · 英文']);assert.throws(()=>library.rename(file,'primary','  '));});
test('existing bilingual resume imports as separate language pages without a provider',async()=>{const markdown=fs.readFileSync('templates/examples/bilingual.md','utf8');const input=core.document({markdown});assert.equal(bilingual.isBilingual(markdown),true);const result=await bilingual.convert(input,{env:{}});assert.equal(result.markdown.split(/^::: page$/m).length,2);assert.equal(result.settings.targetPages,'2');assert.match(result.markdown,/张三/);assert.match(result.markdown,/Jack/);const imported=await require('../lib/import').prepare(Buffer.from(markdown),'resume.md','bilingual');assert.equal(imported.document.markdown.split(/^::: page$/m).length,2);assert.equal(require('../lib/import').contentAudit(markdown,imported.structure).preserved,true);assert.equal(imported.document.settings.templateId,'bilingual');});
test('single-language translation preserves source and failures never return partial documents',async()=>{for(const text of ['负责产品规划与用户研究，交付100个项目','Managed product discovery and user research for 100 projects']){const input=core.document({markdown:'# 示例姓名\n'+text});await assert.rejects(bilingual.convert(input,{env:{}}),{code:'TRANSLATION_NOT_CONFIGURED'});let called=false;const result=await bilingual.convert(input,{env:{PAPER_TRANSLATION_URL:'https://translator.invalid/completions',PAPER_TRANSLATION_MODEL:'test-model'},fetcher:async(url,options)=>{called=true;const body=JSON.parse(options.body);const items=JSON.parse(body.messages[1].content);return {ok:true,json:async()=>({choices:[{message:{content:JSON.stringify({translations:items.map(item=>({index:item.index,text:item.index===0?'# Example Name':text.includes('Managed')?'负责产品规划与用户研究，交付100个项目':'Managed product discovery and user research for 100 projects'}))})}}]})};}});assert.ok(called);assert.ok(result.markdown.includes(text));assert.match(result.markdown,/100/);await assert.rejects(bilingual.convert(input,{env:{PAPER_TRANSLATION_URL:'x',PAPER_TRANSLATION_MODEL:'y'},fetcher:async()=>({ok:true,json:async()=>({choices:[{message:{content:'{"translations":[]}'}}]})})}),{code:'TRANSLATION_FAILED'});}});

test('public bilingual example renders as one Chinese and one English A4 page without overflow',{timeout:30000},async()=>{
 const document=require('../lib/templates').apply({markdown:fs.readFileSync('templates/examples/bilingual.md','utf8')},'bilingual');
 const file=path.resolve('tmp/tests',randomUUID(),'resume.paper.json'),session=await require('../lib/render').createSession({file});
 try{const result=await session.measure(document,{details:true});assert.equal(result.actualPages,2);assert.deepEqual(result.overflow,[]);}finally{await session.close();}
});
