const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto'),{once}=require('node:events');const store=require('../lib/document-store'),library=require('../lib/library'),renderer=require('../lib/render');
test('empty startup, last resume restoration, explicit links, and editor-only brand navigation',{timeout:45000},async()=>{
 const file=path.resolve('tmp/tests',randomUUID(),'resume.paper.json');const server=require('../lib/server').start({file,port:0,quiet:true});await once(server,'listening');const browser=await renderer.launchBrowser();const url='http://127.0.0.1:'+server.address().port;
 try{const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const open=async suffix=>{await page.goto(url+suffix);await page.evaluate(()=>window.paperReady);};await open('/');assert.equal(await page.locator('#home-view').isVisible(),true);assert.equal(await page.locator('#home-button').getAttribute('role'),null);assert.equal(fs.existsSync(file),false);await page.locator('.brand-logo').click();assert.equal(await page.locator('#home-view').isVisible(),true);
 store.commit(file,{markdown:'# 张三\n原稿'},null);const other=library.create(file,{document:{markdown:'# 李四\n另一份'}});await open('/?resume=primary');assert.equal(await page.locator('#document-name').textContent(),'张三');assert.equal(await page.locator('#home-button').getAttribute('role'),'button');await open('/');assert.equal(new URL(page.url()).searchParams.get('resume'),'primary');
 await open('/?resume='+other.id);await page.locator('#editor').fill('# 李四\n另一份\n最后修改');await page.locator('.brand-logo').click();await page.locator('#home-view').waitFor({state:'visible'});assert.match(store.load(other.file).markdown,/最后修改/);assert.equal(await page.locator('#home-button').getAttribute('role'),null);const homeUrl=page.url();await page.locator('#home-button').click();assert.equal(page.url(),homeUrl);await page.reload();await page.evaluate(()=>window.paperReady);assert.equal(await page.locator('#home-view').isVisible(),true);
 await open('/');assert.equal(new URL(page.url()).searchParams.get('resume'),other.id);assert.match(await page.locator('#editor').inputValue(),/最后修改/);await open('/?resume=primary');assert.equal(await page.locator('#document-name').textContent(),'张三');await page.locator('#home-button').focus();await page.keyboard.press('Enter');await page.locator('#home-view').waitFor({state:'visible'});
 await page.evaluate(()=>localStorage.setItem('paper-resume-last-edited','missing'));await open('/');assert.ok(['primary',other.id].includes(new URL(page.url()).searchParams.get('resume')));assert.equal(await page.locator('#edit-view').isVisible(),true);for(const width of [1440,900,640,390]){await page.setViewportSize({width,height:900});await page.locator('#sidebar-toggle').click();const bounds=await page.evaluate(()=>{const sidebar=document.getElementById('sidebar').getBoundingClientRect(),edit=document.getElementById('edit-view').getBoundingClientRect();return {left:edit.left,right:sidebar.right,top:edit.top,bottom:sidebar.bottom,overflow:document.documentElement.scrollWidth>innerWidth};});assert.ok(width>780?bounds.left>=bounds.right-1:bounds.top>=bounds.bottom-1,JSON.stringify({width,...bounds}));assert.equal(bounds.overflow,false);await page.keyboard.press('Escape');assert.equal(await page.locator('body').evaluate(el=>el.classList.contains('sidebar-open')),false);}assert.deepEqual(errors,[]);
 }finally{await browser.close();await new Promise(r=>server.close(r));}
});
test('CLI serve starts an empty workspace without creating a sample resume',{timeout:15000},async()=>{
 const net=require('node:net');const probe=net.createServer().listen(0,'127.0.0.1');await once(probe,'listening');const port=probe.address().port;await new Promise(r=>probe.close(r));const file=path.resolve('tmp/tests',randomUUID(),'resume.paper.json');const child=require('node:child_process').spawn(process.execPath,['cli.js','serve','--file',file,'--port',String(port)],{stdio:['ignore','pipe','pipe']});
 try{await once(child.stdout,'data');assert.equal(child.exitCode,null);assert.equal(fs.existsSync(file),false);const response=await fetch('http://127.0.0.1:'+port+'/api/documents');assert.deepEqual((await response.json()).documents,[]);}finally{const exited=once(child,'exit');child.kill();await exited;}
});
