const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{randomUUID}=require('node:crypto'),{once}=require('node:events');const core=require('../resume-core'),store=require('../lib/document-store'),images=require('../lib/images'),renderer=require('../lib/render'),{main}=require('../cli');
test('QR corners, photo and logo combinations preserve text geometry and quiet zone',{timeout:30000},async()=>{
 const file=path.resolve('tmp/tests/qr',randomUUID(),'resume.paper.json'),qr='tests/fixtures/qr-example.png';fs.mkdirSync(path.dirname(file),{recursive:true});const base=core.document({markdown:'::: center\n# 张三\n产品经理\n联系方式 · 个人主页\n:::\n\n## 工作经历\n### 示例公司 | 2024 - 至今\n普通段落内容。'});store.commit(file,base,null);const server=require('../lib/server').start({file,port:0,quiet:true});await once(server,'listening');const browser=await renderer.launchBrowser();try{const page=await browser.newPage();await page.goto('http://127.0.0.1:'+server.address().port+'/?view=render');await page.evaluate(()=>window.paperReady);await page.evaluate(()=>document.fonts.ready);const bounds=()=>page.evaluate(()=>[...document.querySelectorAll('#resume .layout-center,#resume h1,#resume h2,#resume h3')].map(el=>{const r=el.getBoundingClientRect();return [r.left,r.top,r.right,r.bottom];}));const baseline=await bounds();
 for(const [index,config] of [{side:'left'},{side:'right'},{side:'left',logo:true},{side:'right',photo:true},{side:'left',photo:true,logo:true},{side:'right',photo:true,logo:true}].entries()){
  const previous=store.load(file);store.commit(file,base,previous.revision);if(config.photo)await main(['image','--file',file,'--input','templates/portrait.png','--kind','photo','--position',config.side]);if(config.logo)await main(['image','--file',file,'--input','templates/portrait.png','--kind','logo','--position',config.side]);await main(['image','--file',file,'--input',qr,'--kind','qr','--position',config.side]);const once=store.load(file);await main(['image','--file',file,'--input',qr,'--kind','qr','--position',config.side]);assert.equal(store.load(file).revision,once.revision);await page.evaluate(d=>window.PaperApp.renderSnapshot(d),once);await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.querySelectorAll('#resume img')].map(i=>i.decode()));});assert.deepEqual(await bounds(),baseline);
  const measured=await page.evaluate(()=>{const qr=document.querySelector('.resume-qr'),rect=el=>{const r=el.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,height:r.height};};return {qr:rect(qr),loaded:qr.naturalWidth>0,images:[...document.querySelectorAll('.resume-header-logo,.resume-photo,.resume-qr')].map(rect),sectionTop:document.querySelector('#resume h2').getBoundingClientRect().top};});assert.ok(measured.loaded);assert.ok(Math.abs(measured.qr.width-measured.qr.height)<1);for(const img of measured.images)assert.ok(img.bottom<measured.sectionTop);for(let i=0;i<measured.images.length;i++)for(const other of measured.images.slice(i+1)){const r=measured.images[i];assert.ok(r.right<=other.left||r.left>=other.right||r.bottom<=other.top||r.top>=other.bottom,'Corner images must not overlap');}await page.locator('#resume').screenshot({path:path.join(path.dirname(file),`case-${index}.png`)});
 }
 const buffer=fs.readFileSync(qr);assert.deepEqual(fs.readFileSync(path.join(images.folder(file),images.image(buffer).name)),buffer);await assert.rejects(main(['image','--file',file,'--input',qr,'--kind','qr','--crop','auto']),/不裁剪/);assert.throws(()=>images.insert(base,buffer,'qr','工作经历'),/左右上角/);
 await page.goto('http://127.0.0.1:'+server.address().port+'/?resume=primary');await page.evaluate(()=>window.paperReady);await page.locator('#image-open').click();await page.locator('#image-kind').selectOption('qr');assert.equal(await page.locator('#image-position').inputValue(),'right');await page.locator('#image-position').selectOption('left');await page.locator('#image-file').setInputFiles(qr);await page.locator('#image-form button[type=submit]').click();await page.locator('#image-dialog').waitFor({state:'hidden'});assert.match(store.load(file).markdown,/!\[二维码-left\]/);const pdf=await page.pdf({format:'A4',preferCSSPageSize:true,printBackground:true});assert.equal((await renderer.dependency('pdf-lib').PDFDocument.load(pdf)).getPageCount(),1);
 const exported=path.join(path.dirname(file),'qr.html');fs.writeFileSync(exported,require('../cli').exportHTML(store.load(file),exported,file));await page.goto('file:///'+exported.replace(/\\/g,'/'));await page.evaluate(async()=>{await document.fonts.ready;await Promise.all([...document.querySelectorAll('img')].map(i=>i.decode()));});assert.equal(await page.locator('.resume-qr').count(),2);
 }finally{await browser.close();await new Promise(r=>server.close(r));}
});
