'use strict';
const fs=require('node:fs');const path=require('node:path');const {createHash}=require('node:crypto');const core=require('../resume-core');
function folder(file){const resolved=path.resolve(file);const parts=resolved.split(path.sep);const index=parts.lastIndexOf('.paper-library');return path.join(index>=0?parts.slice(0,index).join(path.sep):path.dirname(resolved),'.paper-assets');}
function image(buffer){if(buffer.length>2*1024*1024)core.fail('图片不能超过 2MB');let type;if(buffer.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])))type='png';else if(buffer[0]===255&&buffer[1]===216&&buffer[2]===255)type='jpg';else if(buffer.toString('ascii',0,4)==='RIFF'&&buffer.toString('ascii',8,12)==='WEBP')type='webp';else core.fail('图片支持 PNG、JPEG、WebP');return {name:createHash('sha256').update(buffer).digest('hex')+'.'+type,type};}
async function cropBounds(buffer,value){if(!value||value==='none')return undefined;if(value!=='auto'&&!/^\d+(?:,\d+){3}$/.test(value))core.fail('crop 可选 auto、none 或 x,y,width,height 像素矩形');image(buffer);const {createCanvas,loadImage}=require('./render').dependency('@napi-rs/canvas');const original=await loadImage(buffer);if(value!=='auto'){const rect=value.split(',').map(Number);if(rect[2]<1||rect[3]<1||rect[0]+rect[2]>original.width||rect[1]+rect[3]>original.height)core.fail('裁剪矩形超出原图范围');return [...rect,original.width,original.height];}if(original.width*original.height>20000000)core.fail('图片像素过大，自动裁白边最多支持2000万像素');const canvas=createCanvas(original.width,original.height),ctx=canvas.getContext('2d');ctx.drawImage(original,0,0);const {data}=ctx.getImageData(0,0,original.width,original.height);let left=original.width,top=original.height,right=-1,bottom=-1;for(let y=0;y<original.height;y++)for(let x=0;x<original.width;x++){const i=(y*original.width+x)*4;if(data[i+3]>24&&(data[i]<245||data[i+1]<245||data[i+2]<245)){left=Math.min(left,x);right=Math.max(right,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}}if(right<0)return undefined;const padding=Math.max(2,Math.round(Math.min(right-left+1,bottom-top+1)*.02));left=Math.max(0,left-padding);top=Math.max(0,top-padding);right=Math.min(original.width-1,right+padding);bottom=Math.min(original.height-1,bottom+padding);return [left,top,right-left+1,bottom-top+1,original.width,original.height];}
function insert(doc,buffer,kind='photo',heading,file,options={}){if(!['photo','logo','qr'].includes(kind))core.fail('图片用途须为 photo、logo 或 qr');if(kind==='qr'&&(heading||options.crop))core.fail('二维码只放左右上角，保留完整图片和四周空白，不裁剪');const normalized=core.document(doc);const asset=image(buffer);const url='assets/'+asset.name;if(options.position!==undefined&&!['left','right'].includes(options.position))core.fail('图片位置须为 left 或 right');const alt=kind==='photo'?(options.position==='left'?'证件照-左':'证件照'):'标志';const crop=options.crop?' {crop='+options.crop.join(',')+'}':'';const markup=`![${alt}${crop}](${url})`;let markdown=normalized.markdown;
 if(kind==='qr'){const qr=`![二维码-${options.position||'right'}](${url})`;const existing=new RegExp('!\\[二维码-'+(options.position||'right')+'\\]\\([^\\n]+\\)');markdown=existing.test(markdown)?markdown.replace(existing,qr):qr+'\n\n'+markdown;}
 else if(kind==='photo'){const regex=/!\[(?:证件照(?:-左)?|photo)(?: \{crop=[^}]+\})?\]\([^\n]+\)/i;if(regex.test(markdown))markdown=markdown.replace(regex,markup);else markdown=markup+'\n\n'+markdown;}
 else if(!heading){const header=`![标志-${options.position||'left'}${crop}](${url})`;const existing=new RegExp('!\\[标志-(?:左|left|right)(?: \\{crop=[^}]+\\})?\\]\\('+url.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\)');markdown=existing.test(markdown)?markdown.replace(existing,header):header+'\n\n'+markdown;}
 else{const info=core.inspect(markdown).headings.filter(h=>h.title===heading);if(info.length!==1)core.fail('标志标题不存在或不唯一');const lines=markdown.split('\n');const styles=require('../text-style');const parsed=styles.readLineStyle(lines[info[0].line-1]);const existing=/!\[标志(?: \{crop=[^}]+\})?\]\([^\n]+?\)/;const divider=parsed.text.lastIndexOf(' | ');const text=existing.test(parsed.text)?parsed.text.replace(existing,markup):divider>=0?parsed.text.slice(0,divider)+' '+markup+parsed.text.slice(divider):parsed.text+' '+markup;lines[info[0].line-1]=styles.writeLineStyle(text,parsed.style);markdown=lines.join('\n');}
 if(file&&!options.dryRun){const dir=folder(file);fs.mkdirSync(dir,{recursive:true});const destination=path.join(dir,asset.name);if(!fs.existsSync(destination))fs.writeFileSync(destination,buffer,{flag:'wx'});}
 return core.document({...normalized,markdown});}
module.exports={image,insert,folder,cropBounds};
