'use strict';
const fs=require('node:fs');const path=require('node:path');const {randomUUID}=require('node:crypto');const core=require('../resume-core');const store=require('./document-store');const templates=require('./templates');
function root(file){return path.join(path.dirname(path.resolve(file)),'.paper-library');}
function list(file){const result=[];if(fs.existsSync(file)){const doc=store.load(file);result.push({id:'primary',name:displayName(doc,primaryInfo(file)),file:path.resolve(file),revision:doc.revision,updatedAt:doc.updatedAt});}
 const folder=root(file);if(fs.existsSync(folder))for(const id of fs.readdirSync(folder)){if(!/^[a-f0-9-]{36}$/.test(id))continue;const target=path.join(folder,id,'resume.paper.json');if(!fs.existsSync(target))continue;const doc=store.load(target);let info={};try{info=JSON.parse(fs.readFileSync(path.join(folder,id,'info.json'),'utf8'));}catch{}const name=displayName(doc,info);result.push({id,name,file:target,revision:doc.revision,updatedAt:doc.updatedAt});}return result;}
function resolve(file,id='primary'){if(id==='primary')return path.resolve(file);if(!/^[a-f0-9-]{36}$/.test(id))core.fail('无效简历 ID');const target=path.join(root(file),id,'resume.paper.json');if(!fs.existsSync(target))core.fail('找不到简历','DOCUMENT_NOT_FOUND');return target;}
function create(file,{name,template='projects',document}={}){if(name!==undefined&&(typeof name!=='string'||name.length>80))core.fail('名称须为 1–80 个字符');const custom=typeof name==='string'&&Boolean(name.trim());const id=randomUUID();const folder=path.join(root(file),id);fs.mkdirSync(folder,{recursive:true});const target=path.join(folder,'resume.paper.json');const saved=store.commit(target,document||{markdown:templates.sample(template)},null);store.atomicWrite(path.join(folder,'info.json'),{name:custom?name.trim():'',nameMode:custom?'custom':'auto',template});return {id,name:displayName(saved.document,{name:custom?name.trim():'',nameMode:custom?'custom':'auto'}),file:target,...saved};}
function primaryInfo(file){try{return JSON.parse(fs.readFileSync(path.join(root(file),'primary.info.json'),'utf8'));}catch{return {};}}
function displayName(doc,info={}){if(info.name&&(info.nameMode==='custom'||(!info.nameMode&&!['我的简历','新简历','简历'].includes(info.name))))return info.name;const title=core.inspect(doc.markdown).headings[0]?.title;return title&&!['你的姓名','Your Name','你的姓名 / Your Name'].includes(title)?title.slice(0,80):'新简历';}
function rename(file,id,name){if(typeof name!=='string'||!name.trim()||name.trim().length>80)core.fail('名称须为 1–80 个字符');resolve(file,id);const info=id==='primary'?path.join(root(file),'primary.info.json'):path.join(root(file),id,'info.json');let previous={};try{previous=JSON.parse(fs.readFileSync(info,'utf8'));}catch{}fs.mkdirSync(path.dirname(info),{recursive:true});store.atomicWrite(info,{...previous,name:name.trim(),nameMode:'custom'});return {id,name:name.trim()};}
module.exports={root,list,resolve,create,rename,displayName};
